name: Release

on:
  push:
    branches:
      - main

concurrency: ${{github.workflow}}-${{github.ref}}

jobs:
  validate:
    uses: ./.github/workflows/_validate.yml

  release:
    name: Release
    needs: validate
    runs-on: ubuntu-24.04
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          cache: "pnpm"
      - run: pnpm i --frozen-lockfile
      - id: changesets
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          publish: pnpm release
